# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0002_services_stoservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='name',
            new_name='service_type',
        ),
        migrations.AddField(
            model_name='stoservice',
            name='service_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sto.Services'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stoservice',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
